/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbulancesRouteImport } from './routes/ambulances'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as ReportsRouteImport } from './routes/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulancesRoute = AmbulancesRouteImport.update({
  id: '/ambulances',
  path: '/ambulances',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambulances': typeof AmbulancesRoute
  '/appointments': typeof AppointmentsRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambulances': typeof AmbulancesRoute
  '/appointments': typeof AppointmentsRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambulances': typeof AmbulancesRoute
  '/appointments': typeof AppointmentsRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambulances'
    | '/appointments'
    | '/doctors'
    | '/emergency'
    | '/patients'
    | '/pharmacy'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambulances'
    | '/appointments'
    | '/doctors'
    | '/emergency'
    | '/patients'
    | '/pharmacy'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/ambulances'
    | '/appointments'
    | '/doctors'
    | '/emergency'
    | '/patients'
    | '/pharmacy'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbulancesRoute: typeof AmbulancesRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DoctorsRoute: typeof DoctorsRoute
  EmergencyRoute: typeof EmergencyRoute
  PatientsRoute: typeof PatientsRoute
  PharmacyRoute: typeof PharmacyRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulances': {
      id: '/ambulances'
      path: '/ambulances'
      fullPath: '/ambulances'
      preLoaderRoute: typeof AmbulancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbulancesRoute: AmbulancesRoute,
  AppointmentsRoute: AppointmentsRoute,
  DoctorsRoute: DoctorsRoute,
  EmergencyRoute: EmergencyRoute,
  PatientsRoute: PatientsRoute,
  PharmacyRoute: PharmacyRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
